# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.too_many_requests_errors import TooManyRequestsErrors  # noqa: E501
from swagger_client.rest import ApiException


class TestTooManyRequestsErrors(unittest.TestCase):
    """TooManyRequestsErrors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTooManyRequestsErrors(self):
        """Test TooManyRequestsErrors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.too_many_requests_errors.TooManyRequestsErrors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
