# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.schedule_resource_relationships_stop_links import ScheduleResourceRelationshipsStopLinks  # noqa: E501
from swagger_client.rest import ApiException


class TestScheduleResourceRelationshipsStopLinks(unittest.TestCase):
    """ScheduleResourceRelationshipsStopLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduleResourceRelationshipsStopLinks(self):
        """Test ScheduleResourceRelationshipsStopLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.schedule_resource_relationships_stop_links.ScheduleResourceRelationshipsStopLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
