# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.alert_resource_relationships_facility import AlertResourceRelationshipsFacility  # noqa: F401,E501


class AlertResourceRelationships(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'facility': 'AlertResourceRelationshipsFacility'
    }

    attribute_map = {
        'facility': 'facility'
    }

    def __init__(self, facility=None):  # noqa: E501
        """AlertResourceRelationships - a model defined in Swagger"""  # noqa: E501

        self._facility = None
        self.discriminator = None

        if facility is not None:
            self.facility = facility

    @property
    def facility(self):
        """Gets the facility of this AlertResourceRelationships.  # noqa: E501


        :return: The facility of this AlertResourceRelationships.  # noqa: E501
        :rtype: AlertResourceRelationshipsFacility
        """
        return self._facility

    @facility.setter
    def facility(self, facility):
        """Sets the facility of this AlertResourceRelationships.


        :param facility: The facility of this AlertResourceRelationships.  # noqa: E501
        :type: AlertResourceRelationshipsFacility
        """

        self._facility = facility

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AlertResourceRelationships):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
