# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.not_found_source import NotFoundSource  # noqa: F401,E501


class NotFoundErrors(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'status': 'str',
        'source': 'NotFoundSource',
        'code': 'str'
    }

    attribute_map = {
        'title': 'title',
        'status': 'status',
        'source': 'source',
        'code': 'code'
    }

    def __init__(self, title=None, status=None, source=None, code=None):  # noqa: E501
        """NotFoundErrors - a model defined in Swagger"""  # noqa: E501

        self._title = None
        self._status = None
        self._source = None
        self._code = None
        self.discriminator = None

        if title is not None:
            self.title = title
        if status is not None:
            self.status = status
        if source is not None:
            self.source = source
        if code is not None:
            self.code = code

    @property
    def title(self):
        """Gets the title of this NotFoundErrors.  # noqa: E501

        A short, human-readable summary of the problem  # noqa: E501

        :return: The title of this NotFoundErrors.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this NotFoundErrors.

        A short, human-readable summary of the problem  # noqa: E501

        :param title: The title of this NotFoundErrors.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def status(self):
        """Gets the status of this NotFoundErrors.  # noqa: E501

        The HTTP status code applicable to the problem  # noqa: E501

        :return: The status of this NotFoundErrors.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this NotFoundErrors.

        The HTTP status code applicable to the problem  # noqa: E501

        :param status: The status of this NotFoundErrors.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def source(self):
        """Gets the source of this NotFoundErrors.  # noqa: E501


        :return: The source of this NotFoundErrors.  # noqa: E501
        :rtype: NotFoundSource
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this NotFoundErrors.


        :param source: The source of this NotFoundErrors.  # noqa: E501
        :type: NotFoundSource
        """

        self._source = source

    @property
    def code(self):
        """Gets the code of this NotFoundErrors.  # noqa: E501

        An application-specific error code  # noqa: E501

        :return: The code of this NotFoundErrors.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this NotFoundErrors.

        An application-specific error code  # noqa: E501

        :param code: The code of this NotFoundErrors.  # noqa: E501
        :type: str
        """

        self._code = code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NotFoundErrors):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
