# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RouteResourceAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'int',
        'text_color': 'str',
        'sort_order': 'int',
        'short_name': 'str',
        'long_name': 'str',
        'direction_names': 'list[str]',
        'description': 'str',
        'color': 'str'
    }

    attribute_map = {
        'type': 'type',
        'text_color': 'text_color',
        'sort_order': 'sort_order',
        'short_name': 'short_name',
        'long_name': 'long_name',
        'direction_names': 'direction_names',
        'description': 'description',
        'color': 'color'
    }

    def __init__(self, type=None, text_color=None, sort_order=None, short_name=None, long_name=None, direction_names=None, description=None, color=None):  # noqa: E501
        """RouteResourceAttributes - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._text_color = None
        self._sort_order = None
        self._short_name = None
        self._long_name = None
        self._direction_names = None
        self._description = None
        self._color = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if text_color is not None:
            self.text_color = text_color
        if sort_order is not None:
            self.sort_order = sort_order
        if short_name is not None:
            self.short_name = short_name
        if long_name is not None:
            self.long_name = long_name
        if direction_names is not None:
            self.direction_names = direction_names
        if description is not None:
            self.description = description
        if color is not None:
            self.color = color

    @property
    def type(self):
        """Gets the type of this RouteResourceAttributes.  # noqa: E501

        | Value | Name          | Example    | |-------|---------------|------------| | `0`   | Light Rail    | Green Line | | `1`   | Heavy Rail    | Red Line   | | `2`   | Commuter Rail |            | | `3`   | Bus           |            | | `4`   | Ferry         |            |   # noqa: E501

        :return: The type of this RouteResourceAttributes.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RouteResourceAttributes.

        | Value | Name          | Example    | |-------|---------------|------------| | `0`   | Light Rail    | Green Line | | `1`   | Heavy Rail    | Red Line   | | `2`   | Commuter Rail |            | | `3`   | Bus           |            | | `4`   | Ferry         |            |   # noqa: E501

        :param type: The type of this RouteResourceAttributes.  # noqa: E501
        :type: int
        """

        self._type = type

    @property
    def text_color(self):
        """Gets the text_color of this RouteResourceAttributes.  # noqa: E501

        A legible color to use for text drawn against a background of the route's `color` attribute. See [GTFS `routes.txt` `route_text_color`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt).   # noqa: E501

        :return: The text_color of this RouteResourceAttributes.  # noqa: E501
        :rtype: str
        """
        return self._text_color

    @text_color.setter
    def text_color(self, text_color):
        """Sets the text_color of this RouteResourceAttributes.

        A legible color to use for text drawn against a background of the route's `color` attribute. See [GTFS `routes.txt` `route_text_color`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt).   # noqa: E501

        :param text_color: The text_color of this RouteResourceAttributes.  # noqa: E501
        :type: str
        """

        self._text_color = text_color

    @property
    def sort_order(self):
        """Gets the sort_order of this RouteResourceAttributes.  # noqa: E501

        Routes sort in ascending order  # noqa: E501

        :return: The sort_order of this RouteResourceAttributes.  # noqa: E501
        :rtype: int
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order):
        """Sets the sort_order of this RouteResourceAttributes.

        Routes sort in ascending order  # noqa: E501

        :param sort_order: The sort_order of this RouteResourceAttributes.  # noqa: E501
        :type: int
        """

        self._sort_order = sort_order

    @property
    def short_name(self):
        """Gets the short_name of this RouteResourceAttributes.  # noqa: E501

        This will often be a short, abstract identifier like \"32\", \"100X\", or \"Green\" that riders use to identify a route, but which doesn't give any indication of what places the route serves. See [GTFS `routes.txt` `route_short_name`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt).   # noqa: E501

        :return: The short_name of this RouteResourceAttributes.  # noqa: E501
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """Sets the short_name of this RouteResourceAttributes.

        This will often be a short, abstract identifier like \"32\", \"100X\", or \"Green\" that riders use to identify a route, but which doesn't give any indication of what places the route serves. See [GTFS `routes.txt` `route_short_name`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt).   # noqa: E501

        :param short_name: The short_name of this RouteResourceAttributes.  # noqa: E501
        :type: str
        """

        self._short_name = short_name

    @property
    def long_name(self):
        """Gets the long_name of this RouteResourceAttributes.  # noqa: E501

        The full name of a route. This name is generally more descriptive than the `short_name` and will often include the route's destination or stop. See [GTFS `routes.txt` `route_long_name`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt).   # noqa: E501

        :return: The long_name of this RouteResourceAttributes.  # noqa: E501
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name):
        """Sets the long_name of this RouteResourceAttributes.

        The full name of a route. This name is generally more descriptive than the `short_name` and will often include the route's destination or stop. See [GTFS `routes.txt` `route_long_name`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt).   # noqa: E501

        :param long_name: The long_name of this RouteResourceAttributes.  # noqa: E501
        :type: str
        """

        self._long_name = long_name

    @property
    def direction_names(self):
        """Gets the direction_names of this RouteResourceAttributes.  # noqa: E501


        :return: The direction_names of this RouteResourceAttributes.  # noqa: E501
        :rtype: list[str]
        """
        return self._direction_names

    @direction_names.setter
    def direction_names(self, direction_names):
        """Sets the direction_names of this RouteResourceAttributes.


        :param direction_names: The direction_names of this RouteResourceAttributes.  # noqa: E501
        :type: list[str]
        """

        self._direction_names = direction_names

    @property
    def description(self):
        """Gets the description of this RouteResourceAttributes.  # noqa: E501

        Details about stops, schedule, and/or service.  See [GTFS `routes.txt` `route_desc`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt).   # noqa: E501

        :return: The description of this RouteResourceAttributes.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this RouteResourceAttributes.

        Details about stops, schedule, and/or service.  See [GTFS `routes.txt` `route_desc`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt).   # noqa: E501

        :param description: The description of this RouteResourceAttributes.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def color(self):
        """Gets the color of this RouteResourceAttributes.  # noqa: E501

        A color that corresponds to the route, such as the line color on a map.\" See [GTFS `routes.txt` `route_color`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt).   # noqa: E501

        :return: The color of this RouteResourceAttributes.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this RouteResourceAttributes.

        A color that corresponds to the route, such as the line color on a map.\" See [GTFS `routes.txt` `route_color`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt).   # noqa: E501

        :param color: The color of this RouteResourceAttributes.  # noqa: E501
        :type: str
        """

        self._color = color

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RouteResourceAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
