# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TooManyRequestsErrors(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'detail': 'str',
        'code': 'str'
    }

    attribute_map = {
        'status': 'status',
        'detail': 'detail',
        'code': 'code'
    }

    def __init__(self, status=None, detail=None, code=None):  # noqa: E501
        """TooManyRequestsErrors - a model defined in Swagger"""  # noqa: E501

        self._status = None
        self._detail = None
        self._code = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if detail is not None:
            self.detail = detail
        if code is not None:
            self.code = code

    @property
    def status(self):
        """Gets the status of this TooManyRequestsErrors.  # noqa: E501

        The HTTP status code applicable to the problem  # noqa: E501

        :return: The status of this TooManyRequestsErrors.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TooManyRequestsErrors.

        The HTTP status code applicable to the problem  # noqa: E501

        :param status: The status of this TooManyRequestsErrors.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def detail(self):
        """Gets the detail of this TooManyRequestsErrors.  # noqa: E501

        Human-readable summary of the problem  # noqa: E501

        :return: The detail of this TooManyRequestsErrors.  # noqa: E501
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this TooManyRequestsErrors.

        Human-readable summary of the problem  # noqa: E501

        :param detail: The detail of this TooManyRequestsErrors.  # noqa: E501
        :type: str
        """

        self._detail = detail

    @property
    def code(self):
        """Gets the code of this TooManyRequestsErrors.  # noqa: E501

        An application-specific error code  # noqa: E501

        :return: The code of this TooManyRequestsErrors.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this TooManyRequestsErrors.

        An application-specific error code  # noqa: E501

        :param code: The code of this TooManyRequestsErrors.  # noqa: E501
        :type: str
        """

        self._code = code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TooManyRequestsErrors):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
